### ISSUE TITLE
WindowsError: [Error 3] : u'D:/LagouJobInfo/lagou/\u6570\u636e\u6316\u6398'

### ISSUE THREAD

**Issue by Rithard** [lucasxlu/LagouJob#1]
不知道是什么原因？

**Comment by EclipseXuLu** [comment]
新建“D:/LagouJobInfo/lagou/”文件夹再试试...或者直接更改路径目录

**Comment by Rithard** [comment]
我刚刚使用os.makedirs(filepath)成功了，但是又卡在open( filepath, encoding = utf-8)

**Comment by Rithard** [comment]
你使用的Python版本是Python3吗？

**Comment by EclipseXuLu** [comment]
是...

**Comment by Rithard** [comment]
怪不得老是出错

**Comment by DaoQiu** [comment]
建议引入相对路径或者是os.path.join()这种方式，可以兼容到linux环境。

**Comment by lucasxlu** [comment]
>  不知道是什么原因？

新建“D:/LagouJobInfo/lagou/”文件夹再试试...或者直接更改路径目录

> 我刚刚使用os.makedirs(filepath)成功了，但是又卡在open( filepath, encoding = utf-8)
> 
> 你使用的Python版本是Python3吗？

是...

> 建议引入相对路径或者是os.path.join()这种方式，可以兼容到linux环境。

嗯，是的。话说好多天没更新了 T_T
