### ISSUE TITLE
没有PositionAjax.json

### ISSUE THREAD

**Issue by ever-lasting** [lucasxlu/LagouJob#10]
拉勾网异步加载，查看XHR类型请求，只有CompanyAjax.json，根本没有PositionAjax.json请求，请问拉勾网是如何请求服务的，我查了很多资料都显示有PositionAjax.json，请问拉勾网是不是又增加了反爬机制。我是小白，请求指教，谢谢！

**Comment by lucasxlu** [comment]
> 拉勾网异步加载，查看XHR类型请求，只有CompanyAjax.json，根本没有PositionAjax.json请求，请问拉勾网是如何请求服务的，我查了很多资料都显示有PositionAjax.json，请问拉勾网是不是又增加了反爬机制。我是小白，请求指教，谢谢！

你好，因拉勾网PC端接口经常变动，故我的代码是针对H5 (https://m.lagou.com)的，编写爬虫的目的是为了获取数据以供分析，而不是为了爬虫而爬虫。因此对于任何网站都是一样，优先保证爬取：APP>H5>PC Web。:-)
