### ISSUE TITLE
代码没实现反爬虫

### ISSUE THREAD

**Issue by Kevenyf** [lucasxlu/LagouJob#11]
楼主代码有几个问题：
1、没有实现反爬虫，不能一直爬下去
2、通过total_count有多少页判断有多少页，但是有个问题就是total_count判断出来的多少页并不是所有页都是有数据的，到后面返回的result是空的

**Comment by lucasxlu** [comment]
> 楼主代码有几个问题：
> 1、没有实现反爬虫，不能一直爬下去
> 2、通过total_count有多少页判断有多少页，但是有个问题就是total_count判断出来的多少页并不是所有页都是有数据的，到后面返回的result是空的

THX for your advice, I'll fix these issues as soon as possible. 😃
