### ISSUE TITLE
想了解一下楼主的初衷

### ISSUE THREAD

**Issue by qqxiaofeng** [lucasxlu/LagouJob#2]
可以联系一下吗?我qq 1127922405

**Comment by EclipseXuLu** [comment]
> 可以联系一下吗?我qq 1127922405
因为读研会做机器学习，自己想从事数据挖掘数据分析相关领域的工作，所以就自学了python，就拿来联手咯   ^_^

**Comment by lucasxlu** [comment]
> 可以联系一下吗?我qq 1127922405

因为读研会做机器学习，自己想从事数据挖掘数据分析相关领域的工作，所以就自学了python，就拿来联手咯 ^_^
