### ISSUE TITLE
ImportError: No module named 'util'

### ISSUE THREAD

**Issue by RockZhou8** [lucasxlu/LagouJob#3]
Traceback (most recent call last):
  File "lagouspider.py", line 5, in <module>
    from util import toolkit
ImportError: No module named 'util'

**Comment by ghost** [comment]
导入模块，或者将该model放入spider中
http://blog.csdn.net/damotiansheng/article/details/43916881

**Comment by jimmy-walker** [comment]
yes, you are right, put it into spider folder. it will be OK.
