### ISSUE TITLE
Couldn't find a tree builder with the features you requested: html5lib

### ISSUE THREAD

**Issue by huzhyi21** [lucasxlu/LagouJob#7]
运行spider时，出现如下错误： 
  File "C:\Users\Admin\Documents\PythonSpyder\LagouJob\spider\jobdetail_spider.py", line 30, in crawl_job_detail
    soup = BeautifulSoup(response.text, 'html5lib')

  File "C:\Users\Admin\Anaconda3\lib\site-packages\bs4\__init__.py", line 156, in __init__
    if isinstance(features, str):

FeatureNotFound: Couldn't find a tree builder with the features you requested: html5lib. Do you need to install a parser library?

注：我已经安装了html5lib, 不知道这个问题应该如何解决？ 谢谢
运行环境：windows 7, anaconda, python 3.5

**Comment by lucasxlu** [comment]
> 运行spider时，出现如下错误：
> File "C:\Users\Admin\Documents\PythonSpyder\LagouJob\spider\jobdetail_spider.py", line 30, in crawl_job_detail
> soup = BeautifulSoup(response.text, 'html5lib')
> 
> File "C:\Users\Admin\Anaconda3\lib\site-packages\bs4_init_.py", line 156, in init
> if isinstance(features, str):
> 
> FeatureNotFound: Couldn't find a tree builder with the features you requested: html5lib. Do you need to install a parser library?
> 
> 注：我已经安装了html5lib, 不知道这个问题应该如何解决？ 谢谢
> 运行环境：windows 7, anaconda, python 3.5

Did you install all of the libraries included in __requirements.txt__?
If it fails again, you can try __lxml__ or __html.parser__ instead.
